
use tauri::Window;
use uuid::Uuid;
use crate::action;
use std::path::Path;

#[tauri::command]
pub fn get_uuid() -> String {
  Uuid::new_v4().to_string()
}

#[tauri::command]
pub fn block_websites() {
  action::block_websites::block_websites(
    Path::new("/etc/hosts"),
    vec!["baidu.com", "www.baidu.com"],
    "### generated by tomatoboat, please DO NOT modify ###"
  );
}

#[tauri::command]
pub fn unblock_websites() {
  action::block_websites::unblock_websites(
    Path::new("/etc/hosts"),
    "### generated by tomatoboat, please DO NOT modify ###"
  );
}

#[tauri::command]
pub fn start_clock(window: Window, start_time: u64, duration: u64) {
  action::clock::start_clock(window, start_time, duration);
}
